version: '3.8'
services:
  test:
    volumes:
      - ./src/main:/app/src/main
    ports:
      - "9230:7777"
    build:
      context: .
      dockerfile: Dockerfile.debug
    restart: always
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: